name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      run: docker build -t iptoasn-webservice -f docker/Dockerfile .
    - name: Test Docker image
      run: |
        # Start container in background
        docker run -d --name test-container -p 53661:53661 iptoasn-webservice
        
        # Wait a moment for the service to start
        sleep 10
        
        # Check if container is running
        docker ps | grep test-container
        
        # Basic health check (if service has one)
        timeout 30 bash -c 'until docker logs test-container 2>&1 | grep -q "listening\|started\|ready"; do sleep 1; done' || echo "Service may still be initializing"
        
        # Clean up
        docker stop test-container
        docker rm test-container
